type LarsElem = number
type Lars = LarsElem[]
type Laquo = Lars
type Boing = Laquo
type Haha = string
type ClosingTypeNested = { number: number[], other: Boing}
type ClosingTimePayload = { timeOfDay: string, nested: ClosingTypeNested, closing: ClosingTimePayload }
type PartReqPayload = {partName: Haha}
type PosPayload = {position: string, partName: string}
type PartOKPayload = {partName: string}
type CarPayload = {partName: string, modelName: string}
type ShouldNotBeIncluded1 = string[] | boolean
type ShouldNotBeIncluded2 = number | ShouldNotBeIncluded1
type ShouldNotBeIncluded3 = { a: string, b: string, c: number | string }
type ShouldNotBeIncluded4 = {field1: number, field2: ShouldNotBeIncluded2}

type LarsElem1 = number
type Lars1 = LarsElem[]
type Laquo1 = Lars
type Boing1 = Laquo
type Haha1 = string
type ClosingTypeNested1 = { number: number[], other: Boing}
type ClosingTimePayload1 = { timeOfDay: string, nested: ClosingTypeNested1, closing: ClosingTimePayload1 }
type PartReqPayload1 = {partName: Haha}
type PosPayload1 = {position: string, partName: string}
type PartOKPayload1 = {partName: string}
type CarPayload1 = {partName: string, modelName: string}
type ShouldNotBeIncluded11 = string[] | boolean
type ShouldNotBeIncluded21 = number | ShouldNotBeIncluded11
type ShouldNotBeIncluded31 = { a: string, b: string, c: number | string }
type ShouldNotBeIncluded41 = {field1: number, field2: ShouldNotBeIncluded21}

type LarsElem2 = number
type Lars2 = LarsElem[]
type Laquo2 = Lars
type Boing2 = Laquo
type Haha2 = string
type ClosingTypeNested2 = { number: number[], other: Boing2}
type ClosingTimePayload2 = { timeOfDay: string, nested: ClosingTypeNested2, closing: ClosingTimePayload2 }
type PartReqPayload2 = {partName: Haha}
type PosPayload2 = {position: string, partName: string}
type PartOKPayload2 = {partName: string}
type CarPayload2 = {partName: string, modelName: string}
type ShouldNotBeIncluded12 = string[] | boolean
type ShouldNotBeIncluded22 = number | ShouldNotBeIncluded1
type ShouldNotBeIncluded32 = { a: string, b: string, c: number | string }
type ShouldNotBeIncluded42 = {field1: number, field2: ShouldNotBeIncluded22}

type LarsElem3 = number
type Lars3 = LarsElem3[]
type Laquo3 = Lars
type Boing3 = Laquo
type Haha3 = string
type ClosingTypeNested3 = { number: number[], other: Boing}
type ClosingTimePayload3 = { timeOfDay: string, nested: ClosingTypeNested3, closing: ClosingTimePayload3 }
type PartReqPayload3 = {partName: Haha}
type PosPayload3 = {position: string, partName: string}
type PartOKPayload3 = {partName: string}
type CarPayload3 = {partName: string, modelName: string}
type ShouldNotBeIncluded13 = string[] | boolean
type ShouldNotBeIncluded23 = number | ShouldNotBeIncluded13
type ShouldNotBeIncluded33 = { a: string, b: string, c: number | string }
type ShouldNotBeIncluded43 = {field1: number, field2: ShouldNotBeIncluded23}